remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin,
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tic-tac" # possible values: default or tic-tac

style: data # possible values: dev, data, ciber, design or wild.
title: 'Projet 1'
description: 'SQL & BI - Toys & Models'
# type: ''
# main_image: 'header.PNG' # http or relative path to image
show_clone: false
show_toc: true
lang: en